### ISSUE TITLE
Bug - Autocompletion for static and self is incomplete.

### ISSUE THREAD

**Issue by hotoiledgoblinsack** [Peekmo/atom-autocomplete-php#101]
Hello

(This was split off from pull request #99.)

At the moment, autocompletion of the **self** and **static** keywords is not complete, only static properties, methods and constants are listed. **static** is currently not implemented yet (which can be resolved with pull request #99).

What needs to be done:
  * In a *static* method, **static** should behave like **self** (with added late-static binding, but this does not matter for us, I think).
  * In a *non-static* method, **static** should behave like **$this**, in the sense that you can call non-static class methods with the keyword.
  * In a *non-static* method, **self** also behaves like **$this**, in the same way as **static** does.

In short, autocompletion of these keywords needs to become aware of whether the method completion is happening in is a static method or not (`isInFunction` can probably be expanded or built upon for this).

All of these are *valid* PHP code:
```
// A non-static method.
public function testStaticMethodFromThisContext()
{
    $this->someClassMethodThatIsNotStatic();
    self::someClassMethodThatIsNotStatic();
    static::someClassMethodThatIsNotStatic();
}
```

Whilst all of these are *invalid* PHP code:

```
// A static method.
public static function testStaticMethodFromStaticContext()
{
    $this->someClassMethodThatIsNotStatic();
    self::someClassMethodThatIsNotStatic();
    static::someClassMethodThatIsNotStatic();
}
```

See also issue #38 and the PHP documentation [1].

[1] https://secure.php.net/manual/en/language.oop5.late-static-bindings.php

**Comment by hotoiledgoblinsack** [comment]
@Peekmo I'm seriously considering whether we shouldn't mark this as "Won't fix" and put a list of features/things we won't support in the README. I don't think any developer following good practice will use `self` of `static` in a non-static method for non-static method access (i.e. as `$this`, using it in non-static methods for static method access is fine). Furthermore, this would require context sensitive autocompletion as we would need to analyze the current method that autocompletion is happening in, which seems like a lot of development time for something that seems more like PHP sadness than intended behavior ;-).

**Comment by Peekmo** [comment]
I agree with you, I was thinking about that. I'm waiting 1 more week, I have some idea to experiment before ;)

**Comment by hotoiledgoblinsack** [comment]
Just like the other issue, this is now present in the README as "Won't Fix (For Now)". So I'll close this for now (less clutter in the issue list). Feel free to reopen if you decide to do more experimenting or even remove it from the README if you succeeded in implementing it!
