### ISSUE TITLE
Enhancement - Autocomplete of `use` statements

### ISSUE THREAD

**Issue by girvo** [Peekmo/atom-autocomplete-php#102]
A really nice feature that PHPStorm has that nearly every other PHP autocomplete (including my favourite, Komodo) lacks, is autocomplete fuzzy matching of `use` statements.

An example: 

```php
<?php
use Twig
```

That would give the autocomplete list, and show every class that has the word `Twig` in it in. Does that make sense? It is a small but amazingly useful feature once you're used to it being there!

Cheers,
Josh

**Comment by Peekmo** [comment]
Today the fuzzy is working on the full namespace of every classes.

So every classes with "Twig" should be in your suggestions as you ask for here no?

**Comment by girvo** [comment]
It doesn't appear to be working in this Symfony project, no. I'm going to turn off a couple other plugins to see if it's being caused by something else and get back to you!

**Comment by Peekmo** [comment]
I'm using this plugin on symfony2 projects everydays and it works like that.

If you have autocomplete in your PHP files, the problem could come from somewhere else, if you don't, it's perhaps a misconfiguration of the plugin itself.

**Comment by girvo** [comment]
I agree, which is why I thought it's possibly caused by another plugin :) I'll take a look at verify what's causing it tomorrow and get back to you

**Comment by hotoiledgoblinsack** [comment]
I'll take the fact that there has been no response as a good thing, meaning that this is no longer an issue ;-). Feel free to open a new ticket or ask for help if this is still a problem.
