### ISSUE TITLE
in 0.10.6 on windows,$this-> it does not work

### ISSUE THREAD

**Issue by zzwind** [Peekmo/atom-autocomplete-php#105]
in 0.10.4 it is works,how can i to do?
sorry my English.

**Comment by zzwind** [comment]
When run Atom Autocomplete Php : Configuration, it take a  "Incorrect setup!" error.
but my setting is not to changed.

**Comment by Peekmo** [comment]
That's normal that the configuration command does not works on windows (https://github.com/Peekmo/atom-autocomplete-php/issues/93) but that's weird that you don't have autocomplete..

That's weird however that 0.10.6 doesn't work but 0.10.4 works..

I don't have any idea for the moment..

**Comment by Peekmo** [comment]
Hello,

I just tried on a fresh install of the plugin on windows, and the completion works.
The problem is on your side (perhaps an other plugin that deactivate mine ?)

**Comment by zzwind** [comment]
When reinstall plugin, it works , thanks for your help
