### ISSUE TITLE
MD5 is deprecated, use md5 instead

### ISSUE THREAD

**Issue by okonomiyaki3000** [Peekmo/atom-autocomplete-php#109]
Tried to update to 0.10.8 but got this warning:

    npm WARN deprecated MD5@1.2.1: deprecated, use lowercase 'md5@2.x' from now on

Also other errors but I suspect those are more of a problem with our network. Anyway, I couldn't update.

**Comment by Peekmo** [comment]
Hi,
Thank you for the report !

**Comment by okonomiyaki3000** [comment]
Great! Unfortunately, I still can't update. Seems like a network probably that you probably can't do anything about but I get this message when running `apm update` from the command line:

```
npm ERR! git fetch -a origin (https://github.com/saschagehlich/autocomplete-plus.git) fatal: Unable to find remote helper for 'https'
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "<path to atom's local node.exe>" "<path to npm-cli.js>" "--globalconfig" "<path to global .apmrc>" "--userconfig" "<path to user .apmrc>" "install" "<temp path to package>" "--target=0.30.6" "--arch=ia32" "--msvs_version=2010"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code 128

npm ERR! Command failed: fatal: Unable to find remote helper for 'https'
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

I doubt there's anything you can do about it but, if you have any idea, I'd appreciate it. I was able to update some other unrelated plugins though so apm is not entirely broken.

**Comment by Peekmo** [comment]
I tried to remove autocomplete-plus from package's dependencies (because autocomplete-plus is now part of the atom core)

It should resolve your issue.

**Comment by okonomiyaki3000** [comment]
Thanks, it worked!
