### ISSUE TITLE
Question - What does onDidChangeCursorPosition in abstract-provider do?

### ISSUE THREAD

**Issue by hotoiledgoblinsack** [Peekmo/atom-autocomplete-php#117]
Hello

I was wondering about a certain part of the code in `abstract-provider`:

```
editor.onDidChangeCursorPosition (event) =>
    # return # Temporary

    if @isHovering == false
        return
    markerProperties =
        containsBufferPosition: event.newBufferPosition
    markers = event.cursor.editor.findMarkers markerProperties
    for key,marker of markers
        for allKey,allMarker of @allMarkers[editor.getLongTitle()]
            if marker.id == allMarker.id
                @gotoFromWord(event.cursor.editor, marker.getProperties().term)
                break
```

What is this code supposed to be doing? This does not seem to influence alt-click at all, so I presume it has something to do with the keyboard version of goto. I've also noticed that sometimes when I move my cursor this code decides it's a good idea to try and navigate to a class while I never used the appropriate keyboard shortcut.

I don't really dare to touch it since it's purpose it not entirely clear, help would be appreciated ;-) @Peekmo @CWDN

**Comment by CWDN** [comment]
It's to get the click event for the markers. 

It's not with the other click event because that uses the clicked elements text to work out what goto to use and as the markers don't have any content it couldn't be done that way. Also doing it this way means we can use the markers properties to get the click element data.

**Comment by hotoiledgoblinsack** [comment]
Ah, I see now, it handles alt-clicking class names inside comment blocks. Now it makes sense, thanks for your explanation, this ticket can be closed ;-). I added a comment on top of it in pull request #116.

**Comment by Peekmo** [comment]
Thank you for your explanations :)
