### ISSUE TITLE
Bug - ClassMapRefresh also includes classes from this package.

### ISSUE THREAD

**Issue by hotoiledgoblinsack** [Peekmo/atom-autocomplete-php#119]
Hello

It seems like the `get_declared_classes` in `ClassMapRefresh` is also fetching classes from the package itself. When autocompleting the classes in my project, classes such as `Peekmo\AutocompletePhp\Tools` are also showing up.

Perhaps it would be possible to put a single PHP file somewhere that does `get_declared_classes` and calling it via the PHP executable directly so it only returns the internal classes from PHP?

Thanks in advance

**Comment by Peekmo** [comment]
Or just find a way to get only PHP internal classes. I'm not a really big fan of "subprocesses"
