### ISSUE TITLE
Question - Indentation level?

### ISSUE THREAD

**Issue by hotoiledgoblinsack** [Peekmo/atom-autocomplete-php#125]
Hello

I see that some files use an indentation level of 4 spaces and others an indentation level of 2 spaces. It would probably be a good idea to make all indenting consistent on one level (I would be willing to do this). My personal preference goes out to 4 spaces as its probably most common from other languages (and also used on the PHP side). I was wondering what your preferred indentation level was?

Thanks in advance

**Comment by Peekmo** [comment]
It should be 4,
There were 2 somewhere, because somewhere I read that coffeescript files are not transpiled if they don't have 2 spaces indentation. That's false ^^
