### ISSUE TITLE
Auto complete from required files

### ISSUE THREAD

**Issue by yotamN** [Peekmo/atom-autocomplete-php#128]
The autocomplete in the current file is good but I can't get autocomplete from external files, for example I did this: `require_once 'simple_html_dom.php` and I don't get file_get_html in the autocomplete, I miss something?

Edit: I don't get auto complete for lots of things, I'm not sure it's a problem with external files, I also don't get $this autocomplete or functions, just the built in functions actually

**Comment by Peekmo** [comment]
Hello,

This plugin rely on [composer](https://getcomposer.org/) in order to work. If your project is not managed with composer, the plugin will not work. Sorry
