### ISSUE TITLE
Bug - Tooltip not nicely removed

### ISSUE THREAD

**Issue by Peekmo** [Peekmo/atom-autocomplete-php#132]
@hotoiledgoblinsack did you noticed that ?

When you get the tooltip, it disappears, but, you can't click on the zone where the tooltip were anymore

**Comment by hotoiledgoblinsack** [comment]
I literally just noticed it. I think this is because the tooltip is not hidden, just the opacity is set to 0, causing mouse events to still be caught by the tooltip. I added the following code locally:
```
# In showTooltipFor:
@$(@popover).css('display', 'block')

# in hideTooltip:
@$(@popover).css('display', 'none')
```

Which seems to fix it.

**Comment by Peekmo** [comment]
I pushed something that move it to the left, it works too^^

**Comment by hotoiledgoblinsack** [comment]
Ok, I see that that should push it outside the editor (and still underneath the tree view), which works as well.
