### ISSUE TITLE
Bug - static-provider is never invoked.

### ISSUE THREAD

**Issue by hotoiledgoblinsack** [Peekmo/atom-autocomplete-php#142]
Hello

I think that static-provider is never being used: `SomeClass::` is giving me autocompletion from the autocomplete-provider (and thus listing all methods, static or otherwise). I think there are two options:
  * Make the regex in autocomplete-provider more strict to not autocomplete after a `::`.
  * Drop `static-provider`, add an `isStatic` for each member in Tools.php, fetch the splitter in autocomplete-provider using `elements = prefix.split(/(?:\-\>|::)/)`, which will then be the second-last element in the returned array and can be used to deduce whether only members with isStatic should be shown or not (i.e. `if splitter == '::'`).

In the further future, all of this should probably adhere to #127, but as I don't think any sane developer will currently use `SomeClass::` inside `SomeClass` itself to access private non-static members, I don't think it's that important at the moment.

Thanks in advance

**Comment by Peekmo** [comment]
The best thing would be to drop ```static-provider``` 
But weird that it's not used anymore, probably because ```::``` has been added in autocomplete-provider.

**Comment by hotoiledgoblinsack** [comment]
Ok, I'm currently working on this in a branch enhancement-consolidate-providers, that will turn the `self`, `static`, `parent` and autocomplete providers into a single member-provider that only works after a `->` or a `::`, also fixing a few other bugs in the process.

I'll also be taking a look at #127 whilst doing this, but no guarantees on this front ;-).

**Comment by hotoiledgoblinsack** [comment]
I think this can be closed, as `static-provider` is now merged into `member-provider`.
