### ISSUE TITLE
provide php constants

### ISSUE THREAD

**Issue by SebSept** [Peekmo/atom-autocomplete-php#149]
Php has a lot of predefined constants. PHP_EOL, JSON_PRETTY_PRINT as examples.

I suppose it won't be hard to provide it since we can grab them in php with 
```(php)
get_defined_constants();
```

http://php.net/manual/en/function.get-defined-constants.php

It could be nice to have theses constants. 

Thanks for that package :)

**Comment by hotoiledgoblinsack** [comment]
Good idea! I implemented this in pull request #161 .
