### ISSUE TITLE
Padawan

### ISSUE THREAD

**Issue by MineyMe** [Peekmo/atom-autocomplete-php#15]
Hello

I see that this plugin works by using vendor/autoload.php to index the code. I just wanted to drop a link here to the [Padawan project](https://github.com/mkusher/padawan.php) which aims to do the same but offers a separate editor-agnostic server, which you may be able to hook into without duplicating efforts. Either way there aren't many plugins or efforts like this around (which seems strange, since PHP is a very popular language), so thanks for this effort!

**Comment by Peekmo** [comment]
Hello,

Not bad, I'll take a look on that.
Thank you ;)

**Comment by Peekmo** [comment]
A too big project.

I prefer to keep my PHP code lighter, without third party dependency, even if it's not perfect, because it's fastest and easier to install.

Regards,
Peekmo
