### ISSUE TITLE
Idea - Show a progress bar in the status bar while indexing.

### ISSUE THREAD

**Issue by Gert-dev** [Peekmo/atom-autocomplete-php#151]
Hello

It might be a neat idea to show a progress bar (Atom has these in its style guide) in the status bar or at the bottom when the indexing is happening, so you know what's going on.

Thanks in advance

**Comment by Peekmo** [comment]
The problem of the progress bar, is that we can't know the differents steps, so it will be 0... then 100% x)

**Comment by hotoiledgoblinsack** [comment]
We can use an indeterminate progress bar instead (see also the Atom styleguide). It just keeps 'scrolling' while something is busy. Other packages such as `build-tools` also use this when a build is running.
