### ISSUE TITLE
Idea - Autocompletion and multiple return types.

### ISSUE THREAD

**Issue by hotoiledgoblinsack** [Peekmo/atom-autocomplete-php#153]
Hello

When you have multiple return types with a single class type, you usually expect auto completion for that class type, for example:

```
/**
 * @return MyClass|null
 */
public function foo() {}
```

Currently, you get no autocompletion at all because we can't deduce what the actual type is. When thinking about it, we indeed can't know for sure that the returned type is a `MyClass`, but seeing as `null` will never have autocompletion (and in most of these cases, such as getters, the programmer can guarantee that there is always a non-null return value), it may be useful to assume `MyClass` anyways.

We would have to think about how far we would go with this, as there is also this case:

```
/**
 * @return MyClass|MyOtherClass|null
 */
public function foo() {}
```

What do we show in this case? I believe that IDE's such as PHPStorm actually list members of *both* classes at the same time, indicating where they are from in the suggestions box, but I'm not entirely sure about that.

Thanks in advance

**Comment by Peekmo** [comment]
In fact, that's a problem. Removing null is a good thing. For the second case, we should not show anything in my opinion, because we can't know, and showing both is clearly bad, because the user don't know that he can get MyClass or MyOtherClass. 

The user will have to add ```/* @var MyCass */``` on its variable.

**Comment by hotoiledgoblinsack** [comment]
I agree, do we remove all basic (non-class) types or just some of them? Perhaps it's best to just strip all of them? Different developers use different types for error conditions. `null` is the proper 'not a reference to an object' type, but some developers still use `false` or even an integer.

**Comment by Peekmo** [comment]
Ok to remove all basic types.
