### ISSUE TITLE
Enhancement - Updating annotations should not happen on save, but when indexing is finished.

### ISSUE THREAD

**Issue by hotoiledgoblinsack** [Peekmo/atom-autocomplete-php#157]
Hello

Sometimes I notice that annotations aren't immediately set correctly after a save. They suddenly correct themselves when you save again. I think this happens because the indexing is not always finished quickly enough, during which the refresh of annotations has already happened. We should look at attaching 'finished' handlers to the indexing process instead so we can refresh the annotations as soon as the indexing finishes.

(If #151 is implemented, we could run all the 'finished' handlers before hiding the progress bar again.)

Thanks in advance

**Comment by Peekmo** [comment]
It needs to trigger an event when indexing is finished so.

**Comment by hotoiledgoblinsack** [comment]
I think I had been interpreting the indexing code incorrectly. The only asynchronous indexing that happens is the class map refresh, which the scanning for annotations is bypassing, as it's directly requesting the methods from PHP by calling `proxy.methods`. In other words, I'll close this as it's not an actual problem.
