### ISSUE TITLE
PHP could not be spawned

### ISSUE THREAD

**Issue by ArakTaiRoth** [Peekmo/atom-autocomplete-php#16]
My development environment is on Windows and I've installed this package. As soon as I try typing anything inside a PHP file I get the titled error, more specifically, "'php' could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process.". This is followed by an error in the console, "Uncaught Error: spawn php ENOENT".

I have verified this is the package causing the problem as the problem disappears as soon as I disable only this package. In addition I have verified that the directory for PHP is in my path, and has been loaded by Atom, by checking process.env.PATH variable while loaded. I also have verified that it is functioning on my system.

**Comment by Peekmo** [comment]
Hello,

I didn't try it on windows for now, and I don't really know how PHP works on this system (I have to test it this week-end).

You can perhaps try to configure the path the your PHP bin into the plugin settings. If you open your command line and if you type "/your/php/bin -v" and you get a result, everything should work.

**Comment by ArakTaiRoth** [comment]
I'm not sure what you mean by "bin"? There is no "bin" folder within my PHP folder. I can however go to the command line and type "php -v" anywhere I am and I get a version #, that's how I verified that it's functioning on my system.

**Comment by Peekmo** [comment]
By "bin" I mean your executable of php.

What is your version of PHP ?

**Comment by ArakTaiRoth** [comment]
I'm not entirely sure then how I go about configuring my path into the plugin settings. Nor why I should have to when the php command itself can run from anywhere in my system (as it is in the Environment PATH).

Version is 5.5.

**Comment by Peekmo** [comment]
To configure the plugin, click on "package" in your preferences, and select "settings" on atom-autocomplete-php plugin.
Then fill the second field with the full path of your executable
![Configuration](http://i.imgur.com/MCtNGJQ.png)

I'm using the "exec" php command sometimes in the plugin, and it's known that this function has some issues on windows. So, I think that perhaps with the full path of the PHP executable, it should work better.

**Comment by ArakTaiRoth** [comment]
Okay, so I need to be honest here, I feel like a complete moron right now. I got the wrong package here. I have autocomplete-php installed, not atom-autocomplete-php. I didn't realize there were 2 different packages providing the same thing, and when searching for autocomplete-php atom, yours is the only one that shows up.

I'm really sorry for wasting your time, I think you can close this issue. I'll raise the issue with the appropriate package this time.

**Comment by Peekmo** [comment]
Oh ok ^^
My package is not release yet on the package manager ;)

Regards,
Peekmo
