### ISSUE TITLE
Question - Create a list of things to do for the 1.0 release?

### ISSUE THREAD

**Issue by hotoiledgoblinsack** [Peekmo/atom-autocomplete-php#180]
Hello

I think it would be a good idea to have somewhere a list of things that still need to be done before we can have a real 1.0 release. That way we have a kind of roadmap to work towards.

I've taken the liberty to close all the current milestones which were finished and created a 1.0.0 milestone that we can assign to tickets that need to be done. I've also removed a couple of unused labels (*invalid* and *duplicate*, as we close issues that have these states immediately anyway). I've already assigned a few issues to this milestone, feel free to add more or remove some you feel aren't needed.

1.0.0 would also be a good time to fix all the minor quirks or annoyances one noticed but didn't fix because it was less important in light of the more serious issues.

Finally, this does not mean we can't have any more releases until 1.0 arrives, but if all tickets matching the milestone are finished, it means we can label the next version as 1.0.

Thanks in advance

**Comment by Peekmo** [comment]
I was planning to do that in fact, great idea.
