### ISSUE TITLE
Autocomplete for external object instance

### ISSUE THREAD

**Issue by harpreetsb** [Peekmo/atom-autocomplete-php#185]
simply
i have class
```php
namespace Model;
use Wplib\Reviews;
use Model\Base;
class Reviewmodel extends Base{
	private $wpReviewClass;
	/**
	 * contructor
	 * @return			nothing
	 */
	public function __construct() {
		parent::__construct();
		$this->wpReviewClass = new Reviews();
	}
        ............................
}
```
now using 
```php
$this->wpReviewClass->{no auto suggests here}
```

**Comment by hotoiledgoblinsack** [comment]
You are missing a docblock with a `@var` tag above your `$wpReviewClass` variable to indicate what type it is:

```php
class Reviewmodel extends Base{
    /**
     * @var Reviews
     */
    private @wpReviewClass;

    ...
```

This should make it work. The exact requirements for autocompletion perhaps weren't entirely clear, the readme on the main page has been updated to contain more detail about what is needed to get autocompletion working properly.

**Comment by harpreetsb** [comment]
@hotoiledgoblinsack  no that does not work either.

**Comment by Peekmo** [comment]
Your project is manage with composer ?

**Comment by harpreetsb** [comment]
Well some part of it.
The `api` folder uses composer, you can see the vendor folder.
the `app` does not, thought he autocomplete I am asking is from this.
In the plugin settings I have mentioned the index.php from this folder. 
But the suggestion does not work for any case.
![selection_020](https://cloud.githubusercontent.com/assets/6584304/10506565/fc946ee2-7336-11e5-9be1-8122e979448b.jpg)

**Comment by Peekmo** [comment]
Ok,

The problem is the following : 
The plugin, in order to work, needs that the opened folder is the root folder of your composer.json. It also needs that your class autoloading is managed by composer.

So, if your class autoloading is managed by composer in your "api" folder, then, if you open your window on the "api" folder, it will work.
For "app", it will, unfortunately, doesn't work.

**Comment by harpreetsb** [comment]
seems I have stick to Komodo Edit then.

**Comment by hotoiledgoblinsack** [comment]
Ok, pull requests to improve the situation are always welcome. If you have any further questions, feel free to open another ticket.
