### ISSUE TITLE
Question - Accessing home folder?

### ISSUE THREAD

**Issue by hotoiledgoblinsack** [Peekmo/atom-autocomplete-php#19]
Hello

I was wondering if there is a reason the package is trying to access my home folder? I have the following filesystem lay-out with an open_basedir restriction:

  * ~ (access not allowed)
    * ~/Projects (access allowed)
      * ~/Projects/MyProject (access allowed)
  * ~/.atom/packages/atom-autocomplete-php/ (access allowed)

For some reason, when opening MyProject, php/parser.php generates a warning that an attempt was made to chdir() to the home folder (~). This message doesn't seem to break any functionality, but I thought I'd ask anyway to be sure this wasn't an unintended side effect.

Thanks in advance

**Comment by Peekmo** [comment]
Hello,

There will be a side effect. In fact, the package is writing an index file in ~/.atom/packages/atom-autocomplete-php/indexes to get all class names. (required for use .... and new .... autocompletion).

Regards,
Peekmo

**Comment by hotoiledgoblinsack** [comment]
After some debugging the error seems to be originating from Tools.php:21 where composer is executed. The error is actually being generated by composer and I think it's using the default working directory (which would then be my home folder). Adding this before that line seems to solve the issue:

```
chdir(Config::get('projectPath'));
```

**Comment by Peekmo** [comment]
Hi,

I'll look if there's no side effect to use a chdir.

Thank you

**Comment by Peekmo** [comment]
Hello,

Could you please tell me if the last version is broken for you ?
Thanks

**Comment by hotoiledgoblinsack** [comment]
Hello, thanks for the commit, I will try to test tomorrow when I have access to my development machine again.

**Comment by hotoiledgoblinsack** [comment]
Seems to be fixed, thanks!

**Comment by Peekmo** [comment]
Thank you :)
