### ISSUE TITLE
Automatic adding of use statements interferes with grouping in rare cases.

### ISSUE THREAD

**Issue by Gert-dev** [Peekmo/atom-autocomplete-php#196]
Hello

It appears the automatic adding of use statements sometimes wrongly interferes with grouping:

```php
use A\B;
use A\B\F; // <-- Inserted here while it should probably be inserted under A\C.
use A\C;
```

This can probably be solved by adding an additional check on the amount of segments.

Thanks in advance

**Comment by Peekmo** [comment]
Why should it be inserted under A\C ?

**Comment by Gert-dev** [comment]
At the moment this is actually an exception that does not conform to the current behavior, which is why I marked it as bug, if you have:

```php
use A\B;
use A\D;
```

... and now add an `A\C`, you get this (correct):

```php
use A\B;
use A\C;
use A\D;
```

Now if you add use `A\E\Test`, you will get (correct):

```php
use A\B;
use A\C;
use A\D;

use A\E\Test;
```

The only reason this issue exists is because `A\B\F` has the same prefix as the existing `A\B`, so it gets treated differently as, say, `A\E`. With the 'add newlines' option disabled (default), this is not so much of a problem, but if it is enabled, the grouping will be messed up and start adding newlines in places it shouldn't, e.g. with the original example:

```php
use A\B;

use A\B\F; // With newlines enabled, there will be extra whitespace (incorrect).
use A\C;
```
