### ISSUE TITLE
Incorrect Composer setup error

### ISSUE THREAD

**Issue by Traverse** [Peekmo/atom-autocomplete-php#201]
Hello I've been receiving the error notification for having an incorrect Composer setup with version 0.18.1 however nothing in my setup changed. I'm on W7x64 and using Atom 1.0.19, it was working before so some change must've broken it?

Edit: I think I've found why it didn't work the question now is how it happened. Basically somehow there was a space in front of the composer path in the settings (which I didn't change). So there must be something going wrong there or it's just a weird accident not sure.

**Comment by Peekmo** [comment]
Hello,

In fact, with the last release, your settings are checked every time you load the package (everytime you start atom so), and everytime you change something in your plugin config. It's to help user to configure the plugin.

For the space before, it's not related, you probably had it before or you add it by accident, but the plugin doesn't change your config (except default values perhaps, but here it's not the case)

**Comment by Traverse** [comment]
Okay thanks for the quick reply, small follow up question then; did it not care about the space before? Because it used to work just fine.

**Comment by Peekmo** [comment]
The command to check the config is not the same that execute commands in for the plugin, so.. perhaps it fails in some case with the space and not in an other. That's weird but I don't have a better explanation ^^

**Comment by Traverse** [comment]
I'll close this up hopefully it's all good, thanks for the quick responses :+1:

**Comment by Peekmo** [comment]
No problem :+1: 

In fact, for every commands, that's PHP that execute composer commands, but for the check, it's nodejs that execute the command, and nodejs is less permissive than PHP ;)

**Comment by spencerthayer** [comment]
Is there a fix for this solution? I'm pretty sick of seeing this error.

<img width="453" alt="screen shot 2015-11-23 at 8 00 29 pm" src="https://cloud.githubusercontent.com/assets/1019815/11355737/e54f7754-921c-11e5-99f0-05929d112d6f.png">
auto-autocomplete-php incorrect setup!
Either php or composer is not correctly set up and as a result PHP autocomplete will not work. Please visit the settings screen to correct this error. If you are not specifying an absolute path for PHP or Composer, make sure they are in your PATH. Feel free to look package’s README for configuration examples.

**Comment by Peekmo** [comment]
Hello,

Does the plugin work for you ? Because this tooltip only appears if you have a wrong configuration.
If it appears and the plugin works, check if you don't have a space before or after your configuration parameters.
