### ISSUE TITLE
Issue in Atom 1.2.0

### ISSUE THREAD

**Issue by vinkla** [Peekmo/atom-autocomplete-php#205]
I'm getting the following error message in return: 

<img width="458" alt="zi3gwd18p1gtaroi0ntbeb1uomtklmtqe1p9qo6diinpwxpzwlz2xev-tj2bg2znen9bynczjyy5m1zq6tezy90iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85" src="https://cloud.githubusercontent.com/assets/499192/11145543/bb4be492-8a06-11e5-9ac8-c85a86aba0f3.png">

**Comment by Peekmo** [comment]
Hi,

How did you get that ? I don't have this issue, but there's an issue with atom 1.2 (alt - click doesn't work)

Regards,
Peekmo

**Comment by vinkla** [comment]
Just popped up when I loaded a file.
