### ISSUE TITLE
Breaks Split Pane functionality

### ISSUE THREAD

**Issue by chrissm79** [Peekmo/atom-autocomplete-php#212]
A bit strange, but I started having issues when attempting to split panes (i.e., cmd-k right) which would cause atom to completely freeze. I completely removed Atom and it's settings ([followed these instructions](https://discuss.atom.io/t/how-to-completely-uninstall-atom-for-mac/9084/12)) and started to re-install packages. When I install atom-autocomlete-php the issue reocurrs. When I uninstall it, it is resolved. I tested this out with Atom v1.3.2 and this being the only package installed. (I noticed the issue on Atom v1.3.1)

**Comment by Peekmo** [comment]
Hello,

I'll have a look, I didn't test atom 1.3.*. But for the older version it works.

**Comment by ecoleman** [comment]
Can confirm I have the same issue, 1.3.2

**Comment by Peekmo** [comment]
I have it too with 1.3.2. I have no idea of the problem. Don't know where to find logs. So, it'll be hard ^^

**Comment by ecoleman** [comment]
```
(anonymous function) (/Applications/A…-editor.js:535)
_.some._.any (/Applications/A…es/unders…:208)
module.exports.TextEditor.getLongTitle (/Applications/A…-editor.js:535)
module.exports.AbstractProvider.registerAnnotations (abstract-provider.coffee:88)
(anonymous function) (abstract-provider.coffee:26)
(anonymous function) (/Applications/A…rkspace.js:287)
(anonymous function) (/Applications/A…rkspace.js:352)
module.exports.Emitter.emit (/Applications/A…/emitter.js:86)
module.exports.PaneContainer.addedPaneItem (/Applications/A…ntainer.js:375)
(anonymous function) (/Applications/A…ntainer.js:353)
(anonymous function) (/Applications/A…ontainer.js:97)
module.exports.Emitter.emit (/Applications/A…/emitter.js:86)
module.exports.PaneContainer.didAddPane (/Applications/A…ntainer.js:293)
module.exports.Pane.setContainer (/Applications/A…src/pane.js:98)
module.exports.PaneAxis.addChild (/Applications/A…ne-axis.js:144)
module.exports.PaneAxis.insertChildAfter (/Applications/A…ne-axis.js:216)
module.exports.Pane.split (/Applications/A…rc/pane.js:710)
module.exports.Pane.splitDown (/Applications/A…rc/pane.js:680)
commandRegistry.add.pane:split-down (/Applications/A…ommands.js:204)
module.exports.CommandRegistry.handleCommandEvent (/Applications/A…egistry.js:260)
(anonymous function) (/Applications/A…-registry.js:3)
module.exports.KeymapManager.dispatchCommandEvent (/Applications/A…manager.js:536)
module.exports.KeymapManager.handleKeyboardEvent (/Applications/A…manager.js:359)
module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/A…-handler.js:97)
(anonymous function) (/Applications/A…t-handler.js:3)
```

Sorry I can't seem to get a full file path from chrome... It would appear something is going wrong in abstract-provider.coffee's registerAnnotations method?

**Comment by Peekmo** [comment]
Thank you,

Where did you get that ?

The issue is from atom ( https://github.com/atom/atom/issues/10060 )
Hope they'll fix it in 1.3 ^^

**Comment by ecoleman** [comment]
I opened developer tools (option-command-i) and went to the “Source Tab”, clicked “Pause” when atom hung

**Comment by chrissm79** [comment]
Confirmed, looks like it is indeed an atom issue. Downloaded Atom Beta and it looks like it's working again.

**Comment by Peekmo** [comment]
atom 1.4 has been released. No more problem.

Regards,
Peekmo
