### ISSUE TITLE
atom-autocomplete-php:namespace command does not work

### ISSUE THREAD

**Issue by umpirsky** [Peekmo/atom-autocomplete-php#213]
I used [import_namespace](https://github.com/erichard/SublimePHPCompanion#import_namespace) in sublime, and I really miss it.

It would be nice if we can add this feature.

**Comment by Peekmo** [comment]
Hello,

The feature already exists, you can press "ctrl - alt - n" or use command "atom autocomplete php : namespace"

Note : it only works if you are in a composer project.

**Comment by umpirsky** [comment]
@Peekmo Thanks for the quick response, really appreciate it!

I tried both, keyboard shortcut and command in several projects. In one it failed with https://github.com/Peekmo/atom-autocomplete-php/issues/23, but that's ok since `composer.json` is not in the root dir. But for others just nothing happens.

I would be happy to debug if you instruct me what I can do to provide more information.

**Comment by Peekmo** [comment]
Can you copy/past your "autoload" sectin of your composer.json and the location of your php files in your project pls ?

**Comment by umpirsky** [comment]
@Peekmo Let's test it on https://github.com/sylius/sylius/ project as an example. I just did - didn't work.

Autoload is in https://github.com/Sylius/Sylius/blob/master/composer.json#L191-L193.

Thanks.

**Comment by umpirsky** [comment]
@Peekmo Any news on this?

**Comment by Peekmo** [comment]
Everything works well for me with Sylius.

The problem you can have is that it will not work in app/AppKernel.php ('cause app/ folder is not in composer's autoloader). But every file in "src" folder should work.

**Comment by umpirsky** [comment]
@Peekmo OK, I tried it and it did't work as I expected, see https://github.com/umpirsky/Sylius/commit/faaa271a2a0d05e1640069a4e98a406ae230ffb1:

* It added namespace on wrong place (minor).
* It added namespace even there was already one defined (minor).
* It added `Sylius\Sylius\Bundle\AddressingBundle` namespace `Sylius\Bundle\AddressingBundle` expected. 

Thanks.

**Comment by Peekmo** [comment]
Sorry, but everything is ok with your example : 

- Why the wrong place ? Top of the file is the right place
- It replaces the namespace if the namespace is wrong, so, it's not an error, it's clearly what is wanted ;)
- The namespace is good according to the composer.json. You have `"psr-0": { "Sylius\\": "src/" }` so everything under src is on Sylius namespace, then, you have Sylius, Bundle, AdressingBundle folder, so, The namespace is `Sylius` (from composer) + `Sylius\Bundle\AddressingBundle` (from folders) = `Sylius\Sylius\Bundle\AddressingBundle`

**Comment by Peekmo** [comment]
As a side note, Sylius components have a different composer.json for each bundle (see https://github.com/umpirsky/Sylius/blob/master/src/Sylius/Bundle/AddressingBundle/composer.json) that's why their namespace doesn't have a "Sylius\" prefix. 

The plugin only look at a composer.json to the root directory of the project.

I think that it's an Sylius issue if their root composer.json autoload section does not match the bundle's namespaces.

**Comment by umpirsky** [comment]
@Peekmo Ah, true, you are right.

But I must disagree that it is a Sylius issue, this is perfectly valid and common in many projects that split across components, like [Symfony](https://github.com/symfony/symfony) for example.

However, it is noted in README that it will work only with `composer.json` in root, so ok.

But, I guess it is not hard to find first `composer.json` by going up to directory tree, right? And it would do the job. Maybe I will submit PR when I get some time.

Thanks.

**Comment by Peekmo** [comment]
No, there is a Sylius issue because the autoloader section of the root composer is not right with component's autoloaders.

Of course, component specific autoloaders is not an issue, but namespaces from different composers MUST match.

In Symfony2, it matches.

**Comment by umpirsky** [comment]
@Peekmo How do you explain auto loader working then if it is a Sylius issue. All classes are autoloaded without any problem. I work on this project for several years and autoloader always worked. So I think it is not a Sylius issue. :)

**Comment by Peekmo** [comment]
It works because of composer.json in each folders. It doesn't break the code, but the autoload from composer.json is inconsistent, that's all ^^
