### ISSUE TITLE
Using a reflection library ?

### ISSUE THREAD

**Issue by Adirelle** [Peekmo/atom-autocomplete-php#22]
You might want to take a look at [php-reflect](https://github.com/llaville/php-reflect), a library and tool that is able to analyze PHP sources without triggering any error. Moreover, it provides extension points, allowing to visit the parsed sources.

**Comment by Peekmo** [comment]
Hello,

Thank you, but that's a really hard decision. I would like to keep things really simple to be efficient and avoid that cannot be managed inside the plugin without copy/past them.

I'll take a look if that's really interesting for this plugin

**Comment by Adirelle** [comment]
About efficiency, spawning a PHP process for each class (which is mandatory to use the Reflection API, since any error in the PHP file would cause a Fatal Error) is far from efficient on windows.

For example, on a fairly small projet (615 classes, mostly from dependencies), getting the data for all the classes takes more than 1 minute (i5 at 3.3Ghz with 8 Gb RAM) :
```
$ time php parser.php /path/to/myproject --classes
{ /* JSON data for 615 classes */ }
real    1m9.805s
user    0m0.000s
sys     0m0.031s
```

Also note that php-reflect come as a phar (though I don't know if it possible to use as it).

**Comment by Peekmo** [comment]
Yes, I know, that's why this process is started only when you open a new project and the result is cached. Once it's done, everything is working well ^^

**Comment by Peekmo** [comment]
Hello,

Finally, no reflection library will be used.
I prefer to keep things simple.

Regards,
