### ISSUE TITLE
Incorrect setup! 1.5.0-beta0

### ISSUE THREAD

**Issue by harikt** [Peekmo/atom-autocomplete-php#227]
Hi, 

I installed the 1.5 beta of atom. I could not open the Auto complete php configuration. It always shows

```
atom-autocomplete-php - Incorrect setup!
Either PHP or Composer is not correctly set up and as a result PHP autocompletion will not work. Please visit the settings screen to correct this error. If you are not specifying an absolute path for PHP or Composer, make sure they are in your PATH. Feel free to look package's README for configuration examples
```

Now I am confused whether I missed any step.

Thank you

**Comment by harikt** [comment]
I guess I found the settings page now. Sorry for this issue created and my sincere  apologies. I didn't find where the settings was..

**Comment by faducase** [comment]
Same issue, what did you do ?

**Comment by Navid-Ivanian** [comment]
> Same issue, what did you do ?
The problem is about the composer installation and path.You have to install composer!Here's the manual:
https://getcomposer.org/download/
And don't forget about the path in package seeting: 
/usr/local/bin/composer

**Comment by 4sh3** [comment]
path? Explain it please

**Comment by mparafiniuk** [comment]
First check where is your composer with command: `whereis composer`. Then open package settings (Ctrl + , -> Packages -> [atom-autocomplete-php] Settings) and in field 'Command to use composer' put correct path from the first step.

**Comment by jairoD** [comment]
hello, can you specify where is de field 'Command to use composer' because i have tried to change the path but i did'nt find this, in setting i just can see a picture but not a field to change

**Comment by mparafiniuk** [comment]
![zrzut ekranu z 2017-10-18 07-56-40](https://user-images.githubusercontent.com/6795513/31702863-0c845228-b3da-11e7-9f75-478eda52fd7d.png)
