### ISSUE TITLE
"Built-in PHP function": Keyboard shortcut for "More.."

### ISSUE THREAD

**Issue by fractalf** [Peekmo/atom-autocomplete-php#231]
Is it possible to make a keybinding to open the "More.." link without having to press with the mouse?

...
description: 'Built-in PHP function.' # Needed or the 'More' button won't show up.
descriptionMoreURL: config.config.php_documentation_base_url.functions + word

**Comment by Peekmo** [comment]
Hello,

The "more" button is managed by the [autocomplete-plus](https://atom.io/packages/autocomplete-plus) package. It seems that it's not possible today, but open an issue to their package if you want this feature :)

Regards,
Peekmo
