### ISSUE TITLE
Failed to get methods

### ISSUE THREAD

**Issue by GijsGoudzwaard** [Peekmo/atom-autocomplete-php#233]
Whenever I save in a class I get the following error:
```
Failed to get methods for Namespace\Of\My\Class
Unexpected end of input
```

**Comment by Peekmo** [comment]
Hello,

That occurs when you have a problem with your class.
E.G : when you implement an interface, but not all the methods (or the wrong way, like a missing "use"), or when there's a parsing error in the file.

You can turn off the alert by unchecking "Errors on file saving showed" in the plugin settings.

**Comment by GijsGoudzwaard** [comment]
That is not the case, everything is working fine when testing in the browser.
I'm not missing any use statements and I am not using an interface.

**Comment by slaughter550** [comment]
Im getting this error message with this simple syntax.

```<?php

namespace Library\Attachments;

class YouTube
{
    public function isPreviewable()
    {
        return true;
    }
}```

**Comment by shouze** [comment]
Yes, me too

**Comment by yue00er** [comment]
Yes, me too!
How to deal with it ?

**Comment by sebdesign** [comment]
Same problem here, I'm on Windows 10 with php 5.6.24.
