### ISSUE TITLE
[Question] Is there a way to navigate back?

### ISSUE THREAD

**Issue by giorgiofellipe** [Peekmo/atom-autocomplete-php#234]
Does this plugin implements some kind of navigation stack? There's some way to navigate back?
Eg.: alt + arrows (on Netbeans)

**Comment by GijsGoudzwaard** [comment]
As you can see in the [keymap](https://github.com/Peekmo/atom-autocomplete-php/blob/master/keymaps/atom-autocomplete-php.cson) there is a goto-backtrack available:
```
'ctrl-shift-Z': 'atom-autocomplete-php:goto-backtrack'
```

**Comment by giorgiofellipe** [comment]
@GijsGoudzwaard thanks!
