### ISSUE TITLE
Can't configure with Composer in ~/.local/bin/composer

### ISSUE THREAD

**Issue by nikaro** [Peekmo/atom-autocomplete-php#238]
Hello,

Almost everything is in the title. The plugin raise an error saying something like « Composer or PHP is not well installed » (not enough time to read).

While `~/.local/bin/` is in `$PATH` environment variable, i had to do `sudo ln -s ~/.local/bin/composer /usr/local/bin/` in order to configure the plugin to use my local Composer. After that I can delete the alias in `/usr/local/bin/` and it still works.

**Comment by Peekmo** [comment]
Hi.

Don't use ~, replaces it with the full path. It should work.

Regards,
Peekmo

**Comment by nikaro** [comment]
Currently it seems to work with `~` (at least it doesn't tell me that Composer is not installed). But the problem is that right after the installation, i can't access to the settings to change the path, because the package refuse to load itself due to my specific path for Composer.

As i understand, the package only looks if Composer is present at `/usr/local/bin/composer` instead of looking in `$PATH` or doing something like `which composer`. May be it's not possible in JavaScript, or to complicated ? I don't know…

It's not a big issue since the documentation clearly says that composer should be in `/usr/local/bin`, and we can get around after the first loading of the package.
