### ISSUE TITLE
Feature Request: Recognize Type Hinting (PHP7)

### ISSUE THREAD

**Issue by mikebronner** [Peekmo/atom-autocomplete-php#243]
I would love to see type hints being analyzed, as well as docblocks. I don't write docblocks anymore in PHP7 because type hints give me everything I need to know. Allowing parsing of type hints in addition to docblocks would be great. :)

**Comment by mikebronner** [comment]
Woot! 👍

**Comment by mikebronner** [comment]
Just installed the update, thanks! Noticed that function parameter type hints are not displaying -- is that a bug, or just not implemented yet?

**Comment by Peekmo** [comment]
Type hints in function parameters was working before php7. 

Could you please give me an example of a class where type hint doesn't work (if you can reproduce outside your projects)

Regards,
Peekmo
