### ISSUE TITLE
High CPU usage when saving often.

### ISSUE THREAD

**Issue by hotoiledgoblinsack** [Peekmo/atom-autocomplete-php#25]
Hello

I'm experiencing high CPU usage (up to the point where my CPU starts heating up and fans start spinning at maximum). This is probably because I save pretty often and each save initiates a rebuild of the index. I'm not entirely sure what can be done about this, but I just wanted to report it anyway so you know it's happening :P.

Thanks in advance

**Comment by Peekmo** [comment]
Hello,

When you're saving, only the index of the file saved is rebuild. But the old index is loaded in memory. It's probably the problem if you're project is very big (with a lot of vendors) when you're saving often.

I'll try to find an optimization, but it will be hard.
Thank you

**Comment by hotoiledgoblinsack** [comment]
Also wanted to mention that the index is also being rebuilt here if non-PHP-files (e.g. JavaScript files) are being saved, which also contributes to the CPU usage.

**Comment by Peekmo** [comment]
It's ok for non php files.

Nothing was done, but in fact, it was a call for nothing thank you.

**Comment by Cronos87** [comment]
Hello.
Thank you for this package.

Maybe you could add a countdown for indexing when saving. I'm part of these people who saves X times for one save. Maybe it could be a beginning of enhancement.

Thank you!

**Comment by hotoiledgoblinsack** [comment]
What @Cronos87 suggests seems like a good idea, some kind of (configurable?) time out before saving. I think you can find a similar setting in atom's settings related to the undo/redo stack. Saving again before the time out runs out would then reset the time out.

I also notice that if quickly type four letters, saving after each letter, one PHP process per save is spawned and all of them keep running happily at the same time, whilst probably only the last one is relevant as it reflects the final state of the text buffer. Perhaps it would be possible to cancel the currently active process if one is already running before starting a new one?

A combination of both would be even neater, I think this would solve most of this ticket for me since I only really audibly hear my CPU usage (the fans spinning up) when the package spawned multiple PHP processes that are all running at the same time.

**Comment by Peekmo** [comment]
Hello,

I'm not a pro of nodejs, but it seems that it's possible to abort a process.
So, I'll try and in fact, this will reduce CPU usage a lot.

I'll try, great idea ;)

**Comment by Peekmo** [comment]
Didn't succeed on aborting a process with nodejs, that works on every platforms. So, I just not send the same command twice while the first one is not finished.

Regards,
Peekmo
