### ISSUE TITLE
unable to uninstall

### ISSUE THREAD

**Issue by donohue76** [Peekmo/atom-autocomplete-php#253]
every time start atom, i get this red warning popup that doesn't stay on screen long enough for me to read any farther than it being an autocomplete-php error. I disabled the and was trying to uninstall and to try reinstalling it, but when I click to uninstall, id presents another error: uninstall failed, package does not exist. So it's disabled now, but i can't uninstall it. Please advise. 

Thanks,
David

**Comment by Peekmo** [comment]
Hello,

Send this issue to atom team, the package uninstallation is not managed by this one. If you don't have an other error than `uninstall failed, package does not exist` I can't help you sorry.

Peekmo
