### ISSUE TITLE
Members of $this are incorrectly shown when adding a dash after method call.

### ISSUE THREAD

**Issue by hotoiledgoblinsack** [Peekmo/atom-autocomplete-php#26]
Hello

It seems that in the most recent release 0.1.10, the members of $this are incorrectly shown after method calls when typing a dash, i.e.:

```
// As soon as the dash '-' is typed, I get completion containing the methods of $this again.
$this->test()-
```

The same happens when typing a greater than sign '>' instead of the dash:

```
$this->test()>
```

Thanks in advance

**Comment by Peekmo** [comment]
Hello,

In fact, I already saw it. I'll try to improve the regex to avoid that.

Thank you for the report.

**Comment by Peekmo** [comment]
Partially fix. There will always be an autocomplete if you write ```$this->get()ddfs``` but not with ```$this->get()-``` or ```$this->get()>``` (or any other special character).

So, I think that it's acceptable.
