### ISSUE TITLE
difference between this and other packages?

### ISSUE THREAD

**Issue by WhatsThePlan** [Peekmo/atom-autocomplete-php#267]
hi im looking for a good setup for php development and found this package and also other packages such as these https://github.com/Gert-dev/php-integrator-autocomplete-plus , https://github.com/Azakur4/autocomplete-php , https://github.com/vinicarlos56/php-composer-autocompletion this one seems to have the most downloads and be the most popular but im a bit confused by the many packages for php-integrator and the choice. does this contain more features than the other packages?

**Comment by Peekmo** [comment]
Hi,

Gert-dev's plugin is a fork of this one. He wanted to split the plugin in little ones.
Azakur4's one was the first released but it doesn't supports anything else than php functions and local classes.
Never tried vinicarlos56's one, but it seems to have less features.

This one have a lot of features for **composer based projects** (autocomplete, auto-namespace, use auto-added, go-to). Not perfect, there's some issues, but it works most of the time.
Gert's one should have the same thing i think, as it is a fork, but don't really know.

Regards,
Peekmo
