### ISSUE TITLE
Overrides redo keybinding in atom

### ISSUE THREAD

**Issue by benkaiser** [Peekmo/atom-autocomplete-php#268]
Is there a reason this is done?

https://github.com/Peekmo/atom-autocomplete-php/blob/2b054edc166a253e61de049555aa36623864f58a/keymaps/atom-autocomplete-php.cson#L4

I just use this package for better autocompletion, didn't expect it to override major keybindings...

**Comment by Peekmo** [comment]
Hello,

No major reason, there's a lot of keybindings in atom, just unluck that it overrides this one. You can remove/change it in your configuration.

Regards,
Peekmo

**Comment by benkaiser** [comment]
Hi Peekmo,

Thanks for your reply,

That is true that there are lots of keybindings in atom, but this a keybinding that is pretty fundamental to any text-editor. I understand it can be overridden in a users configuration but making extra work for users to restore very standard editor keybindings really doesn't seem that user-friendly.

Cheers,
Ben

**Comment by vip9** [comment]
+1 to change it. It took me a lot of time to search what overrides redo.
