### ISSUE TITLE
Freeze or very high CPU usage with method that returns $this.

### ISSUE THREAD

**Issue by hotoiledgoblinsack** [Peekmo/atom-autocomplete-php#27]
Hello

When coding today with version 0.1.10, I noticed that I get very high CPU usage from the PHP process (php binary) spawned when autocompletion is provided. The CPU usage is high enough to end up in Atom completely freezing until I manually kill the spawned PHP processes.

I can reproduce it with the following sample in my codebase:

```
public function __construct()
{
    $this->test()-> // Freeze as soon as the '>' is typed.
}

/**
 * Test
 *
 * @return $this
 */
protected function test()
{

}
```

In the used codebase, `$this` contains quite a bit of methods, but displaying completion using just `$this->` works fine and without much performance impact, which made me suspect there is a bug. I am using PHP 5.5 on the background.

Thanks in advance

**Comment by Peekmo** [comment]
Hello,

I have this bug too, with Symfony2, in a controller when I write $this->getDoctrine()->. But I don't really know the origin. Sometimes I can more than 4-5 xxx->xxx->xxxx->xxx without bug.

I think that it happens on classes with a lot of methods. But I don't know why. I have to investigate.

Thanks for the report.

**Comment by Peekmo** [comment]
Hello,

I changed the way to parse the return value of a method or attribute.
It should not freeze anymore. Could you just please tell me if the last version (0.1.12) is ok for you ?

Regards,
Peekmo

**Comment by Peekmo** [comment]
I get a freeze today again. Probably not fixed so.

**Comment by hotoiledgoblinsack** [comment]
Indeed, wanted to report the same, but less memory usage is always better ;-).

**Comment by Peekmo** [comment]
Hello,

Does the problem occurs on a class that extends an other one ?
Thank you :)

**Comment by hotoiledgoblinsack** [comment]
It was indeed with a class that extended another one and I can't seem to reproduce it anymore with the same code now, thanks :).

**Comment by Peekmo** [comment]
Ok thank you :+1:
