### ISSUE TITLE
Zombie PHP processes after closing Atom

### ISSUE THREAD

**Issue by hndrewaall** [Peekmo/atom-autocomplete-php#275]
I use a few other PHP Atom plugins, but this is the only one that seems to leave `php` processes hanging around after I quit the application. These accumulate with multiple launches/quits of Atom:

![image](https://cloud.githubusercontent.com/assets/3718321/16854829/b0f9084a-49e0-11e6-99de-5a128bc10d82.png)

Running on:
OSX El Capitan 10.11.5
Atom 1.8.0
atom-autocomplete-php 0.18.9

**Comment by Peekmo** [comment]
Hi,

If you start/restart a lot, yes, but after a while, they will disappear.

Regards,
Peekmo
