### ISSUE TITLE
Autocomplete on local variables

### ISSUE THREAD

**Issue by Peekmo** [Peekmo/atom-autocomplete-php#28]
Manage autocomplete on function's local variables.

```php
public function test()
{
     $x = new \DateTime();
     $x->{autocomplete}
}

**Comment by Peekmo** [comment]
@see branch "autocomplete"

**Comment by hotoiledgoblinsack** [comment]
Nice work, the functionality included 0.4.0 is shaping up fairly well, this plugin is getting better and better ;-).

An idea would also be to support the syntax that some IDE's (such as PHPStorm) use for hinting the type of a variable, e.g.

```
public function foo()
{
    /** @var \Namespace\Class $a */
    $a = $this->someMethod()->getSomeProperty();
  
    if ($someCondition) {
        $a-> // shows members of \Namespace\Class, even if getSomeProperty() returns something else.
     }
}
```

Which can even be used to define the type of $this (useful in e.g. `include`-d files):

```
/** @var \Namespace\Class $this */
```

**Comment by alexandernst** [comment]
Intellij IDEA does this like `/* @var $this yii\web\View */`

**Comment by Peekmo** [comment]
Hello,

Normally
```php
public function foo()
{
    /** @var \Namespace\Class $a */
    $a = $this->someMethod()->getSomeProperty();

    if ($someCondition) {
        $a-> // shows members of \Namespace\Class, even if getSomeProperty() returns something else.
     }
}
```
should work.

As describe in the [README](https://github.com/Peekmo/atom-autocomplete-php#the-rules) : 
```In the code, if you don't have autocompletion, you can had a comment **just before** the line with a @var definition```

So you can't define the variable type everywhere in the code, I just parse the comment right before the variable declaration (you can omit the variable name, just **@var \Namespace\Class** will work

**Comment by hotoiledgoblinsack** [comment]
That's pretty neat, at some point in the future it would be neat to have this also work for $this (not sure if it does right now).

Another thing that might be relevant for this ticket is autocompleting local variables outside functions as well as inside them, for example if I have a file that's `require`-d somewhere with:

```
<?php

/** @var \Namespace\Class $a */
$a = someMethod();
$a->{get autocompletion as well}
```

**Comment by Peekmo** [comment]
Hello,

It works on $this since a long time ! ^^ (But only saved options will be available, and the file must not contains fatal errors when saved)

For the autocomplete outside a function, I don't really know. Perhaps I have to allow it when the cursor is outside a class.

**Comment by eclipxe13** [comment]
Please consider using this with the following syntax:
```
/* @var $variable \Namespace\Class */
```
as @alexandernst points its used in Intellij IDEA and also is used in Netbeans

**Comment by hotoiledgoblinsack** [comment]
I've been toying a bit with variable autocompletion and have a *very* simple variant working here [1] (starting with commit 86609150f27e54e6d6170593e734819e369f9585). This seems to work for most of the local variables that are assigned a new object (i.e. `new SomeType`) and it may need improvement, but if this helps you in any way, feel free to use it (or I could create a pull request).

[1] https://github.com/hotoiledgoblinsack/atom-autocomplete-php/commits/experiment-variable-autocompletion

**Comment by Peekmo** [comment]
I'm closing this issue.
A lot has been done, everything else is already in issues.
