### ISSUE TITLE
Indexing files on every run!!

### ISSUE THREAD

**Issue by gholami-mohammad** [Peekmo/atom-autocomplete-php#283]
If I add a PHP project , it starts indexing on each application start up! 
It takes too much time when I open a Symfony2 app and index again on the next run!
How to fix this problem ?

**Comment by Peekmo** [comment]
Hello,

It's desired, 'cause if you do something that the plugin don't see (e.g : composer install new vendors), the only way to sync the index, is to reindex sometimes. And I decided do to it on startup (cause when something doesn't work, everybody restart the software ;))

**Comment by gholami-mohammad** [comment]
It changes some files in vendor directory!! But if you used Netbeans IDE , It not make any change in any file, and if you used vim with Symfony autocomplete plugin, it creates a separate directory for its indexing. When I decide to delete some bundle from my project , it makes 500 internal error!!

**Comment by Peekmo** [comment]
No sorry, the plugin don't change files in vendor directory.
Its index file is in your ~/.atom/package/atom-autocomplete-php/indexes

**Comment by gholami-mohammad** [comment]
Ok, Thank you! I had installed 2 plugins, this plugin and Peekmo/atom-symfony2 plugin for Symfony development, and after installation my vendor files had changed.

**Comment by erropix** [comment]
Hi @Peekmo,

What about an option to add a status bar button for manually re-syncing the indexes instead of every time the editor is launched.

Another way is to check for file modified time and see if it was changed, that will allow partial indexing if any file was changed

Thanks
