### ISSUE TITLE
Cannot be setup correctly.

### ISSUE THREAD

**Issue by robertlayne** [Peekmo/atom-autocomplete-php#285]
When I setup atom-autocomplete-php for drupal7 & 8 it says that the atom-autocomplete-php is not setup correctly. I've installed composer and checked all setting. I can find no problems.

**Comment by Peekmo** [comment]
Hello,
Can you put a screenshot of your configuration please ?

**Comment by ootomaskooo** [comment]
Make sure you reference your composer.phar by specifying the full path (e.g. E:\composer.phar). For some reason it ignores the value from PATH at the moment and returns this error instead.

**Comment by Peekmo** [comment]
Hello,

No answer, so I close this issue.
Feel free to open a new one if needed.

**Comment by robertlayne** [comment]
Dear,

Please allow me to apologize for not being in the office. Sorry…...
