### ISSUE TITLE
Question: Goto not working in Ubuntu

### ISSUE THREAD

**Issue by Luciam91** [Peekmo/atom-autocomplete-php#289]
I'm running Ubuntu 16.04 but clicking through with alt+mouseclick doesn't work as the default behaviour of Ubuntu tries to take over. How do I ensure this works using that keybinding/what keybinding do I need to change to allow for example ctrl+mouseclick?

**Comment by Peekmo** [comment]
Hello,

I will add an option to select altKey or ctrlKey regarding to your issue. But for now, you can use the shortcut (ctrl - alt -g) when you have the cursor on the method/property.

Regards,
Peekmo

**Comment by Luciam91** [comment]
Just wondering if there was ever any update on this made? :)

**Comment by lsilva-kununu** [comment]
I want it too :(

**Comment by Peekmo** [comment]
It's now possible with the latest release to select ctrl instead of alt.
