### ISSUE TITLE
Deprecated selector in `atom-autocomplete-php/styles/peekmo-php-atom-autocomplete.less`

### ISSUE THREAD

**Issue by datitisev** [Peekmo/atom-autocomplete-php#308]
In `atom-autocomplete-php/styles/peekmo-php-atom-autocomplete.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor .comment-clickable .region,
atom-text-editor::shadow .comment-clickable .region` => `atom-text-editor .comment-clickable .region,
atom-text-editor.editor .comment-clickable .region`

* `atom-text-editor .gutter .line-number.override .icon-right,
atom-text-editor::shadow .gutter .line-number.override .icon-right` => `atom-text-editor .gutter .line-number.override .icon-right,
atom-text-editor.editor .gutter .line-number.syntax--override .icon-right`

* `atom-text-editor .gutter .line-number.override .icon-right:before,
atom-text-editor::shadow .gutter .line-number.override .icon-right:before` => `atom-text-editor .gutter .line-number.override .icon-right:before,
atom-text-editor.editor .gutter .line-number.syntax--override .icon-right:before`

* `atom-text-editor .gutter .line-number.implementation .icon-right,
atom-text-editor::shadow .gutter .line-number.implementation .icon-right` => `atom-text-editor .gutter .line-number.implementation .icon-right,
atom-text-editor.editor .gutter .line-number.syntax--implementation .icon-right`

* `atom-text-editor .gutter .line-number.implementation .icon-right:before,
atom-text-editor::shadow .gutter .line-number.implementation .icon-right:before` => `atom-text-editor .gutter .line-number.implementation .icon-right:before,
atom-text-editor.editor .gutter .line-number.syntax--implementation .icon-right:before`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by Peekmo** [comment]
Should be fixed in last version.

Regards,
Peekmo
