### ISSUE TITLE
Function.extractParams is deprecated.

### ISSUE THREAD

**Issue by bhaskardabhi-oviyum** [Peekmo/atom-autocomplete-php#310]
Assigning custom properties to a marker when creating/copying it is
deprecated. Please, consider storing the custom properties you need in
some other object in your package, keyed by the marker's id property.
```
Function.extractParams (/private/var/folders/6f/yxqxylfd30qbn9gm2hs3mm3c0000gn/T/AppTranslocation/6187B810-E41E-434C-AA7B-FD4585D467AE/d/Atom Beta.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:43:14)
MarkerLayer.markRange (/private/var/folders/6f/yxqxylfd30qbn9gm2hs3mm3c0000gn/T/AppTranslocation/6187B810-E41E-434C-AA7B-FD4585D467AE/d/Atom Beta.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker-layer.js:196:71)
DisplayMarkerLayer.markBufferRange (/private/var/folders/6f/yxqxylfd30qbn9gm2hs3mm3c0000gn/T/AppTranslocation/6187B810-E41E-434C-AA7B-FD4585D467AE/d/Atom Beta.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-marker-layer.js:90:62)
FunctionProvider.placeAnnotation (/Users/bhaskardabhi/.atom/packages/atom-autocomplete-php/lib/annotation/abstract-provider.coffee:183:61)
FunctionProvider.<anonymous> (/Users/bhaskardabhi/.atom/packages/atom-autocomplete-php/lib/annotation/abstract-provider.coffee:147:32)
FunctionProvider.registerAnnotations (/Users/bhaskardabhi/.atom/packages/atom-autocomplete-php/lib/annotation/abstract-provider.coffee:150:12)
```

**Comment by umpirsky** [comment]
Same here. Atom 1.13.0.

**Comment by JanGalek** [comment]
Same problem, 1.13.0

**Comment by avratny** [comment]
I´ve got the same error...

`Function.extractParams - /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:43:14
MarkerLayer.markRange - /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker-layer.js:196:71
DisplayMarkerLayer.markBufferRange - /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-marker-layer.js:90:62
FunctionProvider.placeAnnotation - /Users/andreasvratny/.atom/packages/atom-autocomplete-php/lib/annotation/abstract-provider.coffee:183:61
FunctionProvider.<anonymous> - /Users/andreasvratny/.atom/packages/atom-autocomplete-php/lib/annotation/abstract-provider.coffee:147:32
FunctionProvider.registerAnnotations - /Users/andreasvratny/.atom/packages/atom-autocomplete-php/lib/annotation/abstract-provider.coffee:150:12`

**Comment by ElectroWAR** [comment]
Me too,

> 
Assigning custom properties to a marker when creating/copying it is deprecated. Please, consider storing the custom properties you need in some other object in your package, keyed by the marker's id property.

Report Issue
```
Function.extractParams - C:\Users\Wajira.PS\AppData\Local\atom\app-1.13.1\resources\app.asar\node_modules\text-buffer\lib\marker.js:43:14
MarkerLayer.markRange - C:\Users\Wajira.PS\AppData\Local\atom\app-1.13.1\resources\app.asar\node_modules\text-buffer\lib\marker-layer.js:196:71
DisplayMarkerLayer.markBufferRange - C:\Users\Wajira.PS\AppData\Local\atom\app-1.13.1\resources\app.asar\node_modules\text-buffer\lib\display-marker-layer.js:90:62
FunctionProvider.placeAnnotation - C:\Users\Wajira.PS\.atom\packages\atom-autocomplete-php\lib\annotation\abstract-provider.coffee:183:61
FunctionProvider.<anonymous> - C:\Users\Wajira.PS\.atom\packages\atom-autocomplete-php\lib\annotation\abstract-provider.coffee:147:32
FunctionProvider.registerAnnotations - C:\Users\Wajira.PS\.atom\packages\atom-autocomplete-php\lib\annotation\abstract-provider.coffee:150:12
```

**Comment by crashorbo** [comment]
Same here!!

**Comment by vdjkelly** [comment]
```
Function.extractParams - C:\Users\vdjkelly\AppData\Local\atom\app-1.13.1\resources\app.asar\node_modules\text-buffer\lib\marker.js:43:14
MarkerLayer.markRange - C:\Users\vdjkelly\AppData\Local\atom\app-1.13.1\resources\app.asar\node_modules\text-buffer\lib\marker-layer.js:196:71
DisplayMarkerLayer.markBufferRange - C:\Users\vdjkelly\AppData\Local\atom\app-1.13.1\resources\app.asar\node_modules\text-buffer\lib\display-marker-layer.js:90:62
FunctionProvider.placeAnnotation - C:\Users\vdjkelly\.atom\packages\atom-autocomplete-php\lib\annotation\abstract-provider.coffee:183:61
FunctionProvider.<anonymous> - C:\Users\vdjkelly\.atom\packages\atom-autocomplete-php\lib\annotation\abstract-provider.coffee:147:33
FunctionProvider.registerAnnotations - C:\Users\vdjkelly\.atom\packages\atom-autocomplete-php\lib\annotation\abstract-provider.coffee:150:12
```

**Comment by dryror** [comment]
Same problem on atom 1.14.1

**Comment by joseluisq** [comment]
Same issue:

> :warning: 
> 
> Assigning custom properties to a marker when creating/copying it is
deprecated. Please, consider storing the custom properties you need in
some other object in your package, keyed by the marker's id property.

```sh
$ atom -v
Atom    : 1.14.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

**Comment by tiagorvs** [comment]
Same here!!

**Comment by jeffdupont** [comment]
Same

**Comment by sdbruder** [comment]
+1

**Comment by mai92** [comment]
got same error on atom

`Atom    : 1.14.3
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0`

**Comment by 11110101** [comment]
Same here 

`Atom    : 1.14.3
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0`

**Comment by wwhu668** [comment]
Same here

**Comment by 11110101** [comment]
Issue solved 

Atom    : 1.15.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0 @ #

**Comment by jwhulette** [comment]
Error still appearing:
Atom    : 1.15.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

**Comment by thyagobrejao** [comment]
Me too

**Comment by SzabZol** [comment]
Same problem, Atom 1.15.0

**Comment by tgomesfork** [comment]
Same on Atom 1.15.0

**Comment by m1guelpf** [comment]
@Peekmo Are you going to fix this??

**Comment by umpirsky** [comment]
@m1guelpf It's open source, anyone can jump in and fix it. 

@Peekmo Thanks for the hard work and awesome package!

**Comment by jafar-rezaei** [comment]
+1

**Comment by samnela** [comment]
+1   Atom 1.16.0

**Comment by 3dos** [comment]
Same here
`Atom: 1.16.0
Electron: 1.3.13
Chrome: 52.0.2743.82
Node: 6.5.0`

**Comment by Gabb1995** [comment]
Same here on 1.16.0 x64

**Comment by firegore2** [comment]
same

**Comment by dumasjulien** [comment]
Same here

**Comment by m1guelpf** [comment]
@Peekmo Updates?

**Comment by Peekmo** [comment]
Sorry for the time. It was a non blocking and really obscure deprecation (to me), so it took time. I finally found what was the problem.

Regards

**Comment by artggd** [comment]
up

**Comment by ValentinMerlet** [comment]
up !
