### ISSUE TITLE
atom-autocomplete-php:goto not positioning to method

### ISSUE THREAD

**Issue by umpirsky** [Peekmo/atom-autocomplete-php#323]
I always end up at the first line of the file, or, if file is already opened on last position I was in that file. 

[Screencast from 08-03-17 21:29:26.webm.zip](https://github.com/Peekmo/atom-autocomplete-php/files/828884/Screencast.from.08-03-17.21.29.26.webm.zip)

**Comment by nicodmf** [comment]
Idem, but just for method, if i got to a class from a use by exemple, this work.

**Comment by Peekmo** [comment]
Hello,

In fact, it was working on click, but not with the shortcut or command.

**Comment by umpirsky** [comment]
Just updated to `0.23.1`, I can confirm this being fixed, thanks!

@Peekmo How do you use click navigation? `Ctrl+click`? That does nothing for me.

**Comment by Peekmo** [comment]
It's `alt + click`, looking for a way to edit this shortcut, didn't find a nice way for now.

**Comment by umpirsky** [comment]
@Peekmo Does not work for me.

**Comment by Peekmo** [comment]
Strange. Perhaps your OS do something on alt+click ?

Anyway, with the latest version, you can now choose your key between crl, alt and cmd(for mac). You can try again with ctrl perhaps ?

**Comment by umpirsky** [comment]
I'm on Ubuntu. I don't use mouse anyway. ;)

Thanks!
