### ISSUE TITLE
how to setup with vagrant box ?

### ISSUE THREAD

**Issue by michaelnguyen547** [Peekmo/atom-autocomplete-php#327]
I am using Scotch-box [https://box.scotch.io/] as my development environment. The host machine is windows 10. I don't know what to put in under Settings ( composer, PHP, autoloader, classmap files)

Tried /usr/local/bin/composer, /usr/bin/php, vendor/autoload.php - none works as I believe Atom dont know about the virtual machine.

**Comment by Crawleyprint** [comment]
You need to have php and composer installed on your host machine. Other than that, vendor and cache folders should be located in directory shared between host and guest OS.

**Comment by michaelnguyen547** [comment]
it is quite inconvenience and defeats the purpose of vagrant box to some extend.

thanks
