### ISSUE TITLE
Clear the indexes and start a new fresh indexes

### ISSUE THREAD

**Issue by Xety** [Peekmo/atom-autocomplete-php#332]
Hello,
It is possible to clear all indexes and re-index the whole project ?

I'm working with differents framework and it provide a better autocompletion to have a clean indexes for the current project. Actually, i must delete the `indexes` folder to refresh the indexes.

**Comment by pelallemant** [comment]
Hi, 

Same question, is it possible to force the re-indexation of a project ?

In my case, I symlink a project in the vendor/ folder, and it seems that it is not refreshed in the atom autocompletion.
