### ISSUE TITLE
keybinding overwrites redo

### ISSUE THREAD

**Issue by pmgouveia** [Peekmo/atom-autocomplete-php#336]
keybinding ctrl-shift-z overwrites the redo default keybinding... so anoying.

**Comment by Peekmo** [comment]
The default keybinding is ctrl-z on windows and linux, and cmd-z on macos. (Except if they changed recently, but it would be weird.

**Comment by pmgouveia** [comment]
ctrl-z is to undo... ctrl-shit-z is to **redo**

**Comment by Peekmo** [comment]
Hello,

In fact, as I work on mac, I never get that problem. 
With the latest release, the default keybinding has changed.
