### ISSUE TITLE
Go to declaration

### ISSUE THREAD

**Issue by Ciantic** [Peekmo/atom-autocomplete-php#35]
I see that auto complete works, so it must know something, but it doesn't seem to have full symbols support since "Go to declaration" is not working.

**Comment by Peekmo** [comment]
Hello,

"Go to declaration" is not working yes, but what do you mean by "full symbols" ? Is there something to do to tell atom to "go to" the given file ?

Regards,
Peekmo

**Comment by Peekmo** [comment]
According to the message in the chatroom, it's a duplicate of the issue #29

Thank you ;)
