### ISSUE TITLE
Uncaught TypeError: Cannot read property 'autoload' of undefined

### ISSUE THREAD

**Issue by FLEdev** [Peekmo/atom-autocomplete-php#37]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.2
**System**: Ubuntu 15.04
**Thrown From**: [atom-autocomplete-php](https://github.com/Peekmo/atom-autocomplete-php) package, v0.5.0

### Stack Trace

Uncaught TypeError: Cannot read property 'autoload' of undefined

```
At /home/f/.atom/packages/atom-autocomplete-php/lib/services/namespace.coffee:17

TypeError: Cannot read property 'autoload' of undefined
  at Object.module.exports.createNamespace (/home/f/.atom/packages/atom-autocomplete-php/lib/services/namespace.coffee:17:5)
  at atom-workspace.atom.commands.add.atom-autocomplete-php:namespace (/home/f/.atom/packages/atom-autocomplete-php/lib/config.coffee:49:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:241:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:177:20)

```

### Commands

```
     -8:27.1.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -7:48.2.0 timecop:view (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -7:38 debugger:toggle (div.settings-view.pane-item)
  2x -7:28.7.0 atom-php-navigation:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -7:09.1.0 linter:set-bubble-transparent (atom-text-editor.editor.is-focused)
     -6:47.8.0 bracket-matcher:select-inside-brackets (atom-text-editor.editor.is-focused)
     -6:41.5.0 atom-php-navigation:toggle (atom-text-editor.editor.is-focused)
     -6:37.7.0 linter:set-bubble-transparent (atom-text-editor.editor.is-focused)
     -2:28.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -2:21.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:24.5.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -0:24.3.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -0:22.6.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -0:22.5.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -0:22.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:01.4.0 atom-autocomplete-php:namespace (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "lesscompile",
      "lesscompile",
      "linter-php",
      "linter-xmllint",
      "linter-xmllint",
      "linter-phpcs"
    ]
  },
  "atom-autocomplete-php": {}
}
```

### Installed Packages

```coffee
# User
atom-autocomplete-php, v0.5.0
atom-debugger, v0.1.4
atom-minify, v0.2.0
atom-php-navigation, v0.5.0
autoclose-html, v0.18.0
autocomplete-paths, v1.0.2
autocomplete-php, v0.3.6
autocomplete-phpunit, v1.0.2
autocomplete-sass, v0.1.0
color-picker, v2.0.11
compile-watch, v0.1.4
debugger, v0.0.1
documentation-renderer, v0.2.1
file-icons, v1.5.8
filesize, v0.2.0
flex-tool-bar, v0.4.4
git-diff-details, v0.18.0
git-go, v1.0.1
git-log, v0.4.1
language-twig, v1.6.2
less-compiler, v0.6.2
linter, v1.2.4
minimap, v4.12.0
php-composer-completion, v0.3.0
php-debug, v0.1.2
php-twig, v4.0.0
pigments, v0.8.4
sass-compiler, v0.4.0
silent-sync, v1.2.1
tab-control, v0.6.7
tab-numbers, v0.2.0
text-manipulation, v0.6.0
tree-view-git-status, v0.1.2
w3c-validation, v0.2.0
webbox-color, v0.5.8

# Dev
No dev packages
```

**Comment by Peekmo** [comment]
Hello,

Do you have a composer.json in the root folder of you project ?

Regards,

**Comment by cabloo** [comment]
Happens to me too in a project I have `composer.json` nested one level deep (the `server` directory).

Settings for paths don't seem to have an option for location of composer.json - could I set that location manually in "Command to use composer" setting?

**Comment by Peekmo** [comment]
Hello,

That parameter is not configurable today. I'll try to add this parameter today.

Regards,
Peekmo

**Comment by Peekmo** [comment]
Hello,

Finally, that's too hard to handle a composer placed in any directory.
Try to place a fake "composer.json" in the root of your poject that just have a valid "autoload" key. It will do the job.

Sorry, if you have an idea on how to do it, you can make a PR, but for moment, just the composer.json on the root will be read. Anyway, the error will not appear anymore.

Regards,
Peekmo

**Comment by cabloo** [comment]
Is it possible, instead of handling composer in every directory, to handle it either:

1.) By the individual PHP file that's opened (i.e. multiple Composer projects in one Atom project would work). I think this would work by starting at the top level folder of that PHP file and iterating backwards through the file structure until a composer.json is found.
2.) By a specific setting for the location of composer.json (or folder composer.json is in).

**Comment by Peekmo** [comment]
The problem is not to find the composer.json, but it's to parse the "autoload" values. The code is not planned at all to evaluate a path, and if the composer.json is not in the project root folder, the plugin must evaluate a path. That's hard to do with cross platform compatibility.

But if you want to try, you can check this file : https://github.com/Peekmo/atom-autocomplete-php/blob/master/lib/services/namespace.coffee it's there where all the logic is done.

(as a side note, I'm against backward iteration)
