### ISSUE TITLE
Failed to activate the atom-autocomplete-php package (Windows 10)

### ISSUE THREAD

**Issue by zhihuinvshen** [Peekmo/atom-autocomplete-php#388]
![btf4 3ns_ 6_ w_ 7tnmk x](https://user-images.githubusercontent.com/17938078/41951238-d27baa0c-7997-11e8-8df5-0d40d46047f8.png)

This is the erro I met when I trying to install autocomplete-php.
I am using Window 10, and I also have php on XAMPP environment.
How to solve this problem?

**Comment by zhihuinvshen** [comment]
I already solved the first error 
![7y a k7lmbf90 d5pyog 0](https://user-images.githubusercontent.com/17938078/41952250-0b203c4c-799d-11e8-9697-7c87f2d3dfae.png)

Here is how I sloved it:
Download composer at https://getcomposer.org/, and install it. 
Then all you need just use right path on settings. If you didn't see ProgramData folder, just open folder option on your computer, go to "view" and check "show hidden folders". 
![zgyl3reet 48a j77tc th4](https://user-images.githubusercontent.com/17938078/41952264-1c6caca6-799d-11e8-87b1-d1386b373dd9.png)

but I still have problem on the second error, who can help with it?
![4 jc9txj6x6_ebtcwr_ lo0](https://user-images.githubusercontent.com/17938078/41952326-4e5993c8-799d-11e8-9a68-3b15b76c733a.png)

**Comment by kakigorimochi** [comment]
I have the same problem as well!
![image](https://user-images.githubusercontent.com/16938949/42757903-40b65368-8934-11e8-8f84-af7ff4eda0c9.png)

**Comment by NormanEdance** [comment]
Same issue under Ubuntu 18.04

**Comment by anderslundyo** [comment]
Got the same issue. 
Any fixes? 

Tried to give read-write permissions to the packages folder atom-autocomplete-php in user/.atom/packages without any luck, as it was suggested in [https://github.com/Peekmo/atom-autocomplete-php/issues/40]

**Comment by zhihuinvshen** [comment]
> Got the same issue.
> Any fixes?
> 
> Tried to give read-write permissions to the packages folder atom-autocomplete-php in user/.atom/packages without any luck, as it was suggested in [https://github.com/[Peekmo/atom-autocomplete-php/issues/40](https://github.com/Peekmo/atom-autocomplete-php/issues/40)]
