### ISSUE TITLE
Autocomplete doesn't work when namespace is on same line as <?php

### ISSUE THREAD

**Issue by cabloo** [Peekmo/atom-autocomplete-php#43]
The following shows no autocomplete:

```php
<?php namespace Services;

class SomeService
{
    public function __construct()
    {
        $this->{fail}
    }
}
```

While this does:

```php
<?php

namespace Services;

class SomeService
{
    public function __construct()
    {
        $this->{YEAHHH}
    }
}
```

v0.5.0

**Comment by Peekmo** [comment]
Hello,

There will be performance issue if I'm trying to parse the namespace on the same line as PHP tag. I prefer to not implement this. Feel free to open a PR if you have an idea to modify the existing system.

Regards,
Peekmo

**Comment by cabloo** [comment]
Going to hope to see #42 merged and installed soon otherwise I might just pull the code in myself.
