### ISSUE TITLE
Single files / No composer

### ISSUE THREAD

**Issue by Dgame** [Peekmo/atom-autocomplete-php#44]
Should this Plugin work for single files or small projects without composer interaction?
E.g. if I have something like this:

```php
<?php

class Bar {
    public $var_abc = null;
    public $var_xyz = null;
    public $var_foo = null;

    public function foourz() { }
}

class Foo {
    public function foobar($a) {
        return new Bar();
    }

    public function test() {

    }
}

$f = new Foo();
$f->
```

If I type `$f->f` the built in autocompleter show me all identifiers with starts with `f`, even those who aren't in class Foo (e.g. `foourz`) from Bar. I've tried your plugin on Windows 8.1 but I saw no difference.

**Comment by Peekmo** [comment]
Hello

No, the package is only working with composer today. It's planned to be able to make a project that use a single autoload file to work too, but not single files sorry.

Regards,
Peekmo

**Comment by Dgame** [comment]
Ok, but what if my project does not use a composer, because it's small? Can I integrate the composer somehow?

**Comment by Dgame** [comment]
In other words: how can I use your plugin? I understand that I need a composer but not what my project needs so that the composer build a classmap file.

**Comment by Peekmo** [comment]
Your sources autoloader must be managed by composer (see https://getcomposer.org/doc/04-schema.md#autoload)

**Comment by Dgame** [comment]
I have this composer.json:
```
{
    "autoload": {
        "psr-0": { "": "src/" }
    }
}
```

And all files are generated, but the classmap is empty.

**Comment by Dgame** [comment]
@Peekmo  Maybe you should consider to reopen this issue.

I've fixed the composer.json, instead of "src/" I'd to write ".". The classmap looks now like this:
```php
<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Bar' => $baseDir . '/test.php',
    'Foo' => $baseDir . '/test.php',
);

```
Seems to be ok. But I still get unrelated suggestions, so 
```php
$f->foo
```
shows me still `foobar` **and** `foourz`.
