### ISSUE TITLE
Bug - Slashes ignored in extends/implements when resolving alt-click.

### ISSUE THREAD

**Issue by hotoiledgoblinsack** [Peekmo/atom-autocomplete-php#51]
Hello

It appears that, when attempting to alt-click on classes after the extends/implements keyword, backward slashes are treated as word separators. This does not happen for use statements. For example:

```
namespace Foo\SomeNamespace;

use Foo\Bar;

// Holding the alt key underlines only MyBarInterface instead of Bar\MyBarInterface.
interface SomeInterface extends Bar\MyBarInterface
                                    ______________
{
    // ...
}
```

The result of this is that when alt-clicking **MyBarInterface**, you get the dialog asking you what class to open (if there are multiple **MyBarInterface**s present in your code).
The only correct class is, of course, **Foo\Bar\MyBarInterface** (because of the use statement). If **MyBarInterface** is directly imported, there is no issue.

It should be noted that this *does* work correctly in comments and use statements and this feature is already working very well, regardless of this minor issue, thanks!

**Comment by Peekmo** [comment]
Hello,

Could you tell me if you have the problem with the shortcut (ctrl - alt - g) ?

Regards,
Peekmo

**Comment by hotoiledgoblinsack** [comment]
Thanks for your response. When the cursor is on `MyBarInterface`,  `ctrl-alt-g` does indeed have the same problem.

I've also noticed that when alt-clicking `Foo`, it tries to navigate to `Foo` (correct), but when the cursor is on `Foo`, `ctrl-alt-g` also tries to navigate to `MyBarInterface` . This seems to indicate that ctrl-alt-g is not trying to look for `Bar\MyBarInterface`, but instead it moves ahead beyond the slash and looks for just `MyBarInterface`.

**Comment by Peekmo** [comment]
Do you have a real world example please ? 
I cannot reproduce the bug :(

Thank you

**Comment by hotoiledgoblinsack** [comment]
I have the problem in a company code base, so I unfortunately can't share that, but I'll try to explain the setup as best I can (if this still doesn't explain it I'll see if I can create something small that exhibits the problem).
  
With the following code:

```
namespace Foo\SomeNamespace;

use Foo\Bar;

// Holding the alt key underlines only MyBarInterface instead of Bar\MyBarInterface.
interface SomeInterface extends Bar\MyBarInterface
                                    ______________
{
    // ...
}
```

I have the following interfaces:

  * `Foo\Bar\MyBarInterface` (the one that is used in the `extends`).
  * `Foo\SomeNamespace\MyBarInterface` (in the same namespace and folder as `SomeInterface`)
  * `Foo\SomeOtherNamespace\MyBarInterface`

Because alt-click wants to select `MyBarInterface` instead of `Bar\MyBarInterface`, it finds that there are now multiple candidates (the above ones) and shows the pop up. It should actually be looking for `Bar\MyBarInterface` instead. If I only have `Foo\Bar\MyBarInterface` and none of the other `MyBarInterface` interfaces I think it will 'just work' because there are no other interfaces to select (it will just select the first `MyBarInterface` it can find), even though it's not looking for the right interface.

**Comment by hotoiledgoblinsack** [comment]
I've added an example to the same repository as the other ticket [1]. The problem occurs in src/Test/TestClass.php.

[1] https://github.com/hotoiledgoblinsack/autocomplete-php-example

**Comment by Peekmo** [comment]
Oh ok I see. It occurs when it's not the full namespace that is used. That's totally normal because I didn't implement this case.

Thank you for your example, really clear.
