### ISSUE TITLE
Bug - Alt-click asks what class to navigate to when it already knows.

### ISSUE THREAD

**Issue by hotoiledgoblinsack** [Peekmo/atom-autocomplete-php#52]
Hello

Sometimes alt-clicking an identifier will ask you which one you want to open, even when the package actually already knows which one to select (i.e. which one is the correct one):

```
/**
 * @return Foo\BarInterface
 *         ________________
 */
```

Clicking on `Foo\BarInterface` will open a dialog asking me to select any of

  * `Foo\BarInterface`
  * `Foo\BarTestInterface`
  * `Foo\BarSomeInterface`

The only correct one here is, of course, `Foo\BarInterface`, i.e. the alt-click dialog should not pop up at all. Perhaps this has something to do with fuzzy matching going haywire (as the last two also include the text of the first)?

Thanks in advance

**Comment by Peekmo** [comment]
Hello,

Do you have an example please ?
I cannot reproduce the bug :(

**Comment by hotoiledgoblinsack** [comment]
I've posted a small example here [1]. The problem occurs in src/Foo.php.

[1] https://github.com/hotoiledgoblinsack/autocomplete-php-example
