### ISSUE TITLE
Enhancement - Alt-click ignores aliases.

### ISSUE THREAD

**Issue by hotoiledgoblinsack** [Peekmo/atom-autocomplete-php#53]
Hello

This is not really a bug, as I think this just isn't taken into account yet, but namespace aliases are ignored, for example:

```
use Foo\Bar\Test as MyClass;

// No matches found when alt-clicking MyClass. Should go to Foo\Bar\Test.
class B extends MyClass
{

}
```

I rarely use namespace aliasing, but I thought I'd just mention it anyway so you know it exists and can put it on your 'someday' roadmap ;-).

Thanks in advance

**Comment by Peekmo** [comment]
Hello,

It works for me. Perhaps it will work for you too with the lasts changes.
Could you please tell me ?

Regards,
Peekmo

**Comment by hotoiledgoblinsack** [comment]
I can indeed no longer reproduce it with the latest 0.6.7, nor any of the other issues I reported, thanks for your quick response!

**Comment by Peekmo** [comment]
No problem,
Thank you!
