### ISSUE TITLE
Bug - Autocompletion of use statements doesn't cope with slashes.

### ISSUE THREAD

**Issue by hotoiledgoblinsack** [Peekmo/atom-autocomplete-php#54]
Hello

Autocompletion of use statements ignores the already present prefix or text when slashes are present. For example, here I get suggestions (correct):

```
use Foo\Bar\
            /----------------\
            | Foo\Bar\Class1 |
            | Foo\Bar\Class2 |
            | Foo\Bar\Class3 |
            | Foo\Bar\Class4 |
            \----------------/
```

I now select `Foo\Bar\Class1`, but now I get:

```
use Foo\Bar\Foo\Bar\Class1
```

Instead of:

```
use Foo\Bar\Class1
```

I think this has something to do with the slashes again, if you enter:

```
use Foo
```

And now select `Foo\Bar\Class1`, you (correctly) receive:

```
use Foo\Bar\Class1
```

Thanks in advance

**Comment by Peekmo** [comment]
Hello,

Oh yes in fact, I never saw that ^^
Thank you for your reports.

**Comment by clemf** [comment]
I can confirm this bug, just ran into it myself.
