### ISSUE TITLE
Bug - Alt-clicking return type in docblock does not seem to work.

### ISSUE THREAD

**Issue by hotoiledgoblinsack** [Peekmo/atom-autocomplete-php#56]
Hello

In some cases (I recall this working before), alt-clicking the return type in the docblock does not work. It does work in the method itself, so the name is correctly resolved, for example:

```
/**
 * Second function.
 *
 * @param  string     $param1
 * @param  array|null $param2
 *
 * @return FooClass
 */
public function func2($param1, array $param2 = null)
{
    $obj = new FooClass();
    return $obj;
}
```

Alt-clicking `FooClass` in the docblock here does nothing, whilst alt-clicking it after the `new` statement works correctly.

I've taken the liberty to try and do some debugging of this for you to try and help out and found out that the click event in *abstract-goto.coffee:104* is not attached or invoked. It appears that the docblock `@return` only has `.region` as HTML class, which is not part of `clickEventSelectors`, but is part of `hoverEventSelectors`, which is why hovering works, but clicking doesn't. However, simply adding it does not work. I'm not familiar with Atom's internals, but when inspecting the `FooClass` in the docblock in the inspector, the div has no text set:

```
<div class="highlight comment-clickable comment"><div class="region" style="box-sizing: border-box; top: 176px; left: 105px; width: 56px; height: 16px;"></div></div>
```

... causing the click handler to not know what to look for, as the `.text()` method returns an empty string.

Sometimes it also happens that I can't get autocompletion for a method that has a valid docblock and return statement, but seeing as here the docblock isn't correctly parsed, this may be related. I'll test that separately again as soon as you were able to take a look at this one :).

Thanks in advance

**Comment by Peekmo** [comment]
Hello,

The doc block parsing from autocompletion is done in PHP (https://github.com/Peekmo/atom-autocomplete-php/blob/master/php/services/DocParser.php) and for alt - click it's done with ATOM's DOM. For me, I haven't got hovering on doc blocks.. and so, alt-click does not works, but ctrl - alt - g works (the command does not use the DOM). 

Could you please confirm me that the command works ?

Regards,
Peekmo

**Comment by hotoiledgoblinsack** [comment]
When I hover on the docblock using alt, it underlines it, as if I can click it, but clicking then of course doesn't work. I can however indeed confirm that it does work using `ctrl-alt-g`.

**Comment by Peekmo** [comment]
Hello,

The "bug" cames from something that I removed for the moment (see https://github.com/Peekmo/atom-autocomplete-php/blob/master/lib/goto/abstract-goto.coffee#L112) because it was creating other problems.

So, for the moment, consider that it's 'normal' if comment goto does not work with alt-click.

Regards,
Peekmo

**Comment by hotoiledgoblinsack** [comment]
Ok, that's good to know, I took the liberty of taking a peek at @CWDN's fork and it appears he is already experimenting with it (no pressure at CWDN intended though :P).
