### ISSUE TITLE
Bug - Alt hover handlers not reconnected (?) after docblock modifications.

### ISSUE THREAD

**Issue by hotoiledgoblinsack** [Peekmo/atom-autocomplete-php#58]
Hello

I think I figured out one of the issues I was having with alt hovering not triggering in docblocks, it appears they are just not added for newly added comments, for example:

```
/**
 * Test
 *
 * @return SomeType
 */
```

Using alt and hovering over `SomeType` works correctly. However, if you now remove the line with ` * @return SomeType`, save, readd it, and save again, you can now no longer hover over it using the alt key. Closing the file tab and reopening it fixes the problem, so I think the handlers are just not connected for new code in comments (perhaps the file is only scanned once when it is opened)? This does work correctly for code outside comments.

Thanks in advance

**Comment by Peekmo** [comment]
Hello,

That's a known limitation (see https://github.com/Peekmo/atom-autocomplete-php/pull/42)
I add the label bug to this issue anyway

Regards,
Peekmo

**Comment by hotoiledgoblinsack** [comment]
This could be solved with pull request #87 as it removes and readds these markers on file save.

**Comment by Peekmo** [comment]
Your PR partially solve the problem, I think that it's acceptable if it works on file save.
So, I close the issue.

Feel free to reopen it if you want :)
