### ISSUE TITLE
Bug - Alt-clicking a trait method does not navigate to it in the trait.

### ISSUE THREAD

**Issue by hotoiledgoblinsack** [Peekmo/atom-autocomplete-php#63]
Hello

It appears that alt-clicking a method that originates from a trait has no effect, see also [1]. Autocompleting methods from traits already seems to work, so this may be just a missing test to see if the method is present in any of the class' traits.

Thanks in advance

[1] https://github.com/hotoiledgoblinsack/php-autocomplete-test/blob/69e3a670b971c25717716e253a8db854809fa1f3/src/TestNamespace/SomeClass.php#L77

**Comment by Peekmo** [comment]
Hello,

It's a known issue (https://github.com/Peekmo/atom-autocomplete-php/pull/42)

Thanks,
Regards,
