### ISSUE TITLE
Bug - No autocompletion for class instances in some cases.

### ISSUE THREAD

**Issue by hotoiledgoblinsack** [Peekmo/atom-autocomplete-php#65]
Hello

Using my test repository, I sometimes don't get autocompletion for known classes. For example, try receiving autocompletion for the variable `$obj` in method `testImportedClass` in `SomeClass` [1]. It works fine for e.g. `$this` in the same method and I can also alt-click the `FooClass` statement.

It could be that I'm doing something wrong, any input is appreciated.

Thanks in advance

[1] https://github.com/hotoiledgoblinsack/php-autocomplete-test/blob/69e3a670b971c25717716e253a8db854809fa1f3/src/TestNamespace/SomeClass.php#L104

**Comment by Peekmo** [comment]
Hello,

That's not a bug, just a feature not implemented for the moment. (https://github.com/Peekmo/atom-autocomplete-php#so-what-will-not-work-) because it needs a refactoring. I don't really know how to do it for the moment.

Regards,
Peekmo

**Comment by hotoiledgoblinsack** [comment]
Ok, I see that #28 indeed already covers this, I got a little caried away when reporting bugs and thought there was a difference with the PHP's built-in classes.
