### ISSUE TITLE
Freezing Editor

### ISSUE THREAD

**Issue by vinkla** [Peekmo/atom-autocomplete-php#90]
With the latest 0.9.0 the editor freezes when starting to type and the window stops being responsive. When I turn of this plugin it starts to work again. Any ideas why?

**Comment by Peekmo** [comment]
Hello,

It not freeze for me, so I'm not sure. Could you please, try the 0.9.1 please ?

Peekmo

**Comment by vinkla** [comment]
Now it works much better :+1:

**Comment by Peekmo** [comment]
Sorry for the inconvenience ;)

**Comment by vinkla** [comment]
No worries:) Thanks for quick fix!
