### ISSUE TITLE
Issue with composer or php settings on windows

### ISSUE THREAD

**Issue by bolenMozuk** [Peekmo/atom-autocomplete-php#93]
Regardless of how you enter the path to the composer.phar or php.exe it keeps crashing due to incorrect settings. This happens whit the latest version of atom and this plugin.

**Comment by Peekmo** [comment]
Hello,

What do you means by "it keeps crashing" ?

Regards,
Peekmo

**Comment by zzwind** [comment]
Same here,how to fix it?

**Comment by Peekmo** [comment]
What do you means by "crashing" please ?

**Comment by bolenMozuk** [comment]
Hello again.

**Comment by Peekmo** [comment]
The plugin works anyway ? You've got the message but if it was working before, it should works today.

**Comment by zzwind** [comment]
No,it's not work. Is there any log can i send for you?

**Comment by Peekmo** [comment]
Could you try the last version please ?

**Comment by zzwind** [comment]
Last version works for me, Thanks

**Comment by hotoiledgoblinsack** [comment]
I think the returned status codes are different on Windows. Sadly, I have no Windows machine available to debug it.

In `config.coffee` you'll find a method `testConfig` which tests for this and displays these errors (`atom.notifications.addError`). If someone could open up the developer tools (Ctrl-Shift-I), place a breakpoint underneath the `spawnSync` call,  and analyze what the returned `testResult.status` is on Windows both when your setup is correct and incorrect, that would be great. (At the moment the check is just disabled for everyone.)

**Comment by Peekmo** [comment]
I'll have an access to a windows machine this week-end, I planned to try to debug that on this platform ;)

(I have only a Linux machine at home^^)

**Comment by hotoiledgoblinsack** [comment]
I see that you managed to fix it on Windows, great! Would it also be a good idea to reenable the testConfig call before initialization (it is still commented out at the moment)?
